
### Login to get authentication cookie
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "yara@gmail.com",
    "password": "12345678"
}

### Add item to cart
POST http://localhost:5000/api/cart
Content-Type: application/json

{
  "productId": "675735c9237974cd7e215495",
  "quantity": 2
}

### Get cart items
GET http://localhost:5000/api/cart

### Update cart item quantity
PUT http://localhost:5000/api/cart/675738f7237974cd7e21550d
Content-Type: application/json

{
    "productId": "675738f7237974cd7e21550d",
    "quantity": 4
}


### Clear entire cart
DELETE http://localhost:5000/api/cart